=== Zebreus/kronkorkenmapper/res/instruction.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT mapper (picture*)>
<!ELEMENT picture (subpicture*)>
<!ELEMENT subpicture EMPTY>
<!ATTLIST mapper mode (1|2|3|4|5) "2">
<!ATTLIST mapper segment_height CDATA "20">
<!ATTLIST mapper segment_width CDATA "20">
<!ATTLIST mapper picture_directory CDATA #IMPLIED>
<!ATTLIST mapper subpicture_directory CDATA #IMPLIED>
<!ATTLIST picture file CDATA #REQUIRED>
<!ATTLIST picture height CDATA #IMPLIED>
<!ATTLIST picture width CDATA #IMPLIED>
<!ATTLIST subpicture file CDATA #REQUIRED>
<!ATTLIST subpicture amount CDATA "infinite">
<!ATTLIST subpicture shape (square|round) "square">

=== Zebreus/kronkorkenmapper/res/testinstruction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper SYSTEM "instruction.dtd">
<mapper picture_directory="res/bilder/" subpicture_directory="res/kronkorken/">
	<picture file="pilz.png" height="64" width="64">
		<subpicture file="aktionskronkorken.png" amount="423000" />
		<subpicture file="bionade.png" amount="423000" />
		<subpicture file="bitburgerfussball.png" amount="423000" />
		<subpicture file="bl.png" amount="423000" />
		<subpicture file="clausthaler.png" amount="423000" />
		<subpicture file="clausthaler2.png" amount="423000" />
		<subpicture file="colalight.png" amount="423000" />
		<subpicture file="efes.png" amount="423000" />
		<subpicture file="engelbraeu.png" amount="423000" />
		<subpicture file="erdinger.png" amount="423000" />
		<subpicture file="fanta.png" amount="423000" />
		<subpicture file="heylandsbier.png" amount="423000" />
		<subpicture file="kapuziner.png" amount="423000" />
		<subpicture file="karamalz.png" amount="423000" />
		<subpicture file="koestel.png" amount="423000" />
		<subpicture file="licher.png" amount="423000" />
		<subpicture file="minutemaid.png" amount="423000" />
		<subpicture file="mixery.png" amount="423000" />
		<subpicture file="muehlenkoelsch.png" amount="423000" />
		<subpicture file="ohne.png" amount="423000" />
		<subpicture file="paulaner.png" amount="423000" />
		<subpicture file="paulaner2.png" amount="423000" />
		<subpicture file="postbier.png" amount="423000" />
		<subpicture file="rotlicht.png" amount="423000" />
		<subpicture file="schoefferhofergelb.png" amount="423000" />
		<subpicture file="spessartspecht.png" amount="423000" />
		<subpicture file="spiderman.png" amount="423000" />
		<subpicture file="spinne.png" amount="423000" />
		<subpicture file="veltins+.png" amount="423000" />
		<subpicture file="veltinscola.png" amount="423000" />
		<subpicture file="vitamalz.png" amount="423000" />
		<subpicture file="wasserdreieck.png" amount="423000" />
		<subpicture file="zoetlerbier.png" amount="423000" />
	</picture>
</mapper>
